### ISSUE TITLE
Reduce parttime fields (remove `secfrac` and `tzmin`)

### ISSUE THREAD

**Issue by dgkf** [dgkf/parttime#25]
I've been considering whether some of these fields should be collapsed. 

- `secfrac` is a bit redundant with `sec` (we could easily just include the fractional component)
- `tzhour` and `tzmin` could be collapsed into a single `tz` field (I haven't decided yet what the units of this field would be - leaning toward hours since it's most often how tz offsets are communicated). 

Redundancy is inevitable (since you could just as well store everything as seconds + origin with an uncertainty). What makes these specific fields questionable is that they are rarely used in isolation and could easily be recovered from the reduced forms. 

Collapsing these would simplify some of the formatting, reduce the object size and simplify the data structure slightly.

**Comment by billdenney** [comment]
I agree with simplifying both the `secfrac` and `tzhour` and `tzmin` out of the data structure.

For `tz`, a simple numeric offset with whole number and decimal part can handle everything.  Currently, all timezone offsets are multiples of 0.25 hours between -12 and +14 (https://en.wikipedia.org/wiki/List_of_UTC_offsets).

For `secfrac`, I think it makes sense to include the fractional part in the least significant part of the date/time aligning with the ISO 8601 standard (https://en.wikipedia.org/wiki/ISO_8601#General_principles).

**Comment by billdenney** [comment]
To add to the above, I can't think of a scenario where separating the fractional parts would be simpler in a way that would make object use easier.
