### ISSUE TITLE
How to handle valid and invalid date-times

### ISSUE THREAD

**Issue by billdenney** [dgkf/parttime#32]
@bundfussr indicates an important point in https://github.com/pharmaverse/admiral/issues/1315#issuecomment-1195282821:  "I think it would be helpful to get a warning if invalid strings are passed to `as.parttime()`."

I made PR #31 to give some additional examples of valid and invalid strings for use.  What I didn't do in that PR is actually handle them.

Currently, `parttime` returns `NA` for invalid strings.  I agree with @bundfussr that notifying the user would help.  I prefer having an error to a warning when something is invalid (my opinion is that bad input should stop code rather than warnings which are typically ignored by users in my experience).

So, my thoughts on changes are:

1. Invalid input should alert the user (by warning or error)
2. The alert type should default to error (and maybe have an option to convert to a warning)
3. The alert should notify the user of the invalid strings (up to some limit like 5 or 10 unique values)
4. We would need to decide if an empty string is valid or invalid.  (My opinion is that it's invalid; it should be converted to `NA` prior to going into `as.parttime()` if it is really a missing value).
5. `NA` should be valid and result in an `NA` output (this is already the case, but with these changes it should be codified in a test-- if there isn't one already)

**Comment by dgkf** [comment]
Thanks for the detailed write-up. I've been thinking along the same lines as well. You spelled out a workflow that closely aligns with what I was thinking. 

I'd lean toward emitting a warning, since an error would mean that it wouldn't be able to return a vector. This could be configurable, but as a baseline, it would still let parttime return a valid vector for inspection.

**Comment by dgkf** [comment]
Going to close this now that strings that fail to parse emit warnings. Please file a follow-up if you catch any unintended warnings or would expect one in cases where they aren't emitted.
